apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-app
spec:
  params:
    - name: json-string
      type: string
  results:
    - name: eng-desc-result
      description: "Result from Node.js script"
  steps:
    - name: run-quay-image
      image: quay.io/pknezevich/echo-app:latest
      script: |
          #!/bin/sh
          #/usr/local/bin/npm start | tail -n +5 >> $(results.eng-desc-result.path)
          /usr/local/bin/npm start >> $(results.eng-desc-result.path)
          cat $(results.eng-desc-result.path)

          #echo /usr/local/bin/node app.js $(inputs.params.json-string)
          # echo $node_response
          