apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml 
  - deployment.yaml
  - service.yaml
  - route-ui.yaml
  - route-api.yaml
