apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: file-received-event-task
  namespace: ai-odyssey
spec:
  results:
    - description: The precise URL that was fetched by this Task.
      name: url
  steps:
    - name: id
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:  
        - cat
      args:
        - /etc/redhat-release
    - name: echo
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - echo
      args:
        - "In task 1"
  