apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: file-received-finisher-task
  namespace: ai-odyssey
spec:
  steps:
    - name: id
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - cat
      args:
        - /etc/redhat-release
    - name: echo
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - echo
      args:
        - "Finished!"