apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-authorino
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/manifests/operators/openshift-authorino-operator/overlays/tech-preview-v1
    repoURL: https://github.com/na-launch/jenkins-to-tekton.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true