apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: eng2tek-pipeline
  namespace: model-serving
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/na-launch/jenkins-to-tekton-app'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:dd5c8d08d52e304a542921634ebe6b5ff3d63c5f68f6d644e88417859b173ec8'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: run-app
      params:
        - name: jenkinsFile
          value: example2.jenkinsfile
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: run-app
  workspaces:
    - name: output
