apiVersion: batch/v1
kind: Job
metadata:
  name: create-s3-buckets-job
  namespace: minio-server
spec:
  template:
    spec:
      containers:
        - name: minio-client
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              export MC_CONFIG_DIR=/tmp/.mc
              mc alias set myminio "http://minio-service.minio-server.svc.cluster.local:9000" minio minio123

              # Create and validate the first bucket
              mc mb myminio/pipeline-results || { echo "Failed to create pipeline-results bucket"; exit 1; }
              mc ls myminio/pipeline-results > /dev/null || { echo "Bucket pipeline-results does not exist"; exit 1; }
              mc anonymous set public myminio/pipeline-results

              # Create and validate the second bucket
              mc mb myminio/ai-odyssey-llms || { echo "Failed to create ai-odyssey-llms bucket"; exit 1; }
              mc ls myminio/ai-odyssey-llms > /dev/null || { echo "Bucket ai-odyssey-llms does not exist"; exit 1; }
              mc anonymous set public myminio/ai-odyssey-llms

              echo "All buckets created successfully."              
          volumeMounts:
                - name: tmp-mc-config
                  mountPath: /tmp
      volumes:
        - name: tmp-mc-config
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4
