apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JExlYlN5Y0lQdUVVWjFxNHJRREhIdnVPVzFkRElWV1NGMENOYW9XQlg1TURERDZyRE5aWHh5Cg==
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
