---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - namespace.yaml
  - llamacpp-runtime-custom.yaml
  - create-s3-buckets-job.yaml