apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    enable-route: "true"
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-display-name: LlamaCPP-latest
    opendatahub.io/template-name: llamacpp-latest
    openshift.io/display-name: LlamaCPP-latest
  name: llamacpp-latest
  namespace: model-serving
  labels:
    opendatahub.io/dashboard: "true"
spec:
  containers:
    - image: quay.io/stauil/llamacpp-032:latest
      env:
        - name: MODEL_PATH
          value: /mnt/models
        - name: HOST
          value: 0.0.0.0
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
          hostPort: 8001
      securityContext:
        runAsNonRoot: true
  multiModel: false
  supportedModelFormats:
    - name: any
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
