apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: triggertemplate1
  namespace: model-serving
spec:
  params:
    - name: gitrevision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: pipeline-received
        name: triggered-$(uid)
      spec:
        params:
          - name: revision
            value: $(tt.params.gitrevision)
        pipelineRef:
          name: p1-jnk2eng
        workspaces:
          - name: jnk2eng-workspace
            persistentVolumeClaim:
              claimName: jnk2eng-pvc
