kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jnk2eng-pvc
  namespace: model-serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
