apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener1
spec:
# serviceAccountName: triggersa   #TODO depending on the other needs i will set an SA user later.. commented out (For now)
  triggers:
  - bindings:
    - ref: triggerbinding1
    template:
      ref: triggertemplate1