apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: triggertemplate1
  namespace: ai-odyssey
spec:
  params:
  - name: gitrevision
  - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: pipeline-received
        name: triggered-$(uid)
      spec:
        params:
          - name: p-x
            value: "100"
          - name: p-y
            value: "500"
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl)
        pipelineRef:
          name: pipeline-received