apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - admin-group.yaml


patches:
  - target:
      kind: Subscription
      name: openshift-gitops-operator
    path: patch-channel.yaml